# Generated by Django 3.2.25 on 2024-10-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('role', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('symptoms', models.CharField(max_length=500)),
                ('disease', models.CharField(max_length=500)),
                ('count', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('alternates', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=500)),
                ('review', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
